### ISSUE TITLE
Why there are so many packages in DESCRIPTION's Imports and barely any of them is imported in NAMESPACE? 

### ISSUE THREAD

**Issue by MarcinKosinski** [statisticspoland/R_Package_to_API_BDL#1]

**Comment by MarcinKosinski** [comment]
@KaniaKrzysztof I think you should start using roxygen2''s documentation tags for this one, e.g.

```{R}
#' import dplyr
#' importFrom purrr reduce
```

More about the approach is here http://r-pkgs.had.co.nz/namespace.html#imports

**Comment by MarcinKosinski** [comment]
@KaniaKrzysztof first of all I just put an example on what you should include in your package. It wasn't the full list. Secondly the NAMESPACE do not have any imports provided. If you do not understand the issue, let me know and I'll just provide the update for you

**Comment by KaniaKrzysztof** [comment]
All packages were imported:
https://github.com/statisticspoland/R_Package_to_API_BDL/blob/master/R/bdl.R 
and package rebuilded:
https://github.com/statisticspoland/R_Package_to_API_BDL/blob/master/NAMESPACE 
Idk why after reverting commit in RStudio it's still present. I'll try to merge them for clarity.
