### ISSUE TITLE
The repository name

### ISSUE THREAD

**Issue by MarcinKosinski** [statisticspoland/R_Package_to_API_BDL#10]
`R_Package_to_API_BDL` seems tought. Why not using some catchy name for the repository, that relates to the short name of the package? A repository could be named `statisticspoland/rbld` where the package, while still in the development phrase could also by renamed to `rbld`. Think about the other interface for other language that would probably can be named after laguages like
py-bdl and so on. With the `rbld` in the name, you not only have the catchy meanigful name for the repository but also you can distinguish between the `bld` package for R, Python and other languages.

Just a though, but it's better to solve this at the early beginning

**Comment by blakocha** [comment]
Good remark, MarcinKosinski.

**Comment by MarcinKosinski** [comment]
@blakocha I had internal discusion with the author and I've realized it's for organization internal issueses. The nam gonna rename the same
