### ISSUE TITLE
Issues with the installation

### ISSUE THREAD

**Issue by pbiecek** [statisticspoland/R_Package_to_API_BDL#14]
On my Ubuntu 18 the instruction suggested in the README

```
remotes::install_github("statisticspoland/R_Package_to_API_BDL", upgrade = "always", type = "binary")
```
crashes with 
```
Error in i.p(...) : type 'binary' is not supported on this platform
```

This one works

```
remotes::install_github("statisticspoland/R_Package_to_API_BDL")
```

**Comment by KaniaKrzysztof** [comment]
I used that to prevent errors when `install_github()` forced installing source packages on windows machines, which resulted an error if user had no devtools installed. Of course it will not work for linux as it doesn't support binary packages as far as I know. I'll provide additional info on the README for linux users.
