### ISSUE TITLE
search_subjects() get_subjects() returns Failure to get data. Error occured. Status code: 500

### ISSUE THREAD

**Issue by jacekkotowski** [statisticspoland/R_Package_to_API_BDL#16]
get_units() and search_units (search_units(name = "wro") etc. work well, however get and search subjects throws an error Status code:500

search_subjects("lud")
Error in get_request(dir, id, filters, ...) : 
  Failure to get data. Error occured. Status code: 500.

 search_subjects(name = "lud")
Error in get_request(dir, id, filters, ...) : 
Failure to get data. Error occured. Status code: 500.

search_subjects(name = "lud")
Error in get_request(dir, id, filters, ...) : 
Failure to get data. Error occured. Status code: 500.

search_subjects(name = "lud", lang = "pl")
Error in get_request(dir, id, filters, ...) : 
Failure to get data. Error occured. Status code: 500.

get_subjects()
Error in get_request(dir, id, filters, ...) : 
  Failure to get data. Error occured. Status code: 500.

get_subjects(parentId = "011212000000")
Error in get_request(dir, id, filters, ...) : 
  Failure to get data. Error occured. Status code: 500.

search_subjects("zdrowia")
Error in get_request(dir, id, filters, ...) : 
  Failure to get data. Error occured. Status code: 500.

get_subjects(Id = "011212000000")
Error in get_request(dir, id, filters, ...) : 
Failure to get data. Error occured. Status code: 500.

get_units() and search_units (search_units(name = "wro") etc. work well.

**Comment by KaniaKrzysztof** [comment]
Hello, I've tested it both on CRAN and GitHub version and didn't get any 500 code errors. Is it still failing with 500?
