### ISSUE TITLE
Why roxygen2 is in Suggests?

### ISSUE THREAD

**Issue by MarcinKosinski** [statisticspoland/R_Package_to_API_BDL#2]
In this line https://github.com/statisticspoland/R_Package_to_API_BDL/blob/master/DESCRIPTION#L17 one can see that roxygen2 is a suggested package. In this section user specify packages that are needed for a broader usage of the package: like vignettes' execution. None of users will ever need roxygen2 to use your package. This package is meant for developers, where the Suggests section is meant for users.

More http://r-pkgs.had.co.nz/description.html

**Comment by KaniaKrzysztof** [comment]
Fixed in c700442

**Comment by MarcinKosinski** [comment]
@KaniaKrzysztof I think the roxygen2 is still in the Suggests

**Comment by KaniaKrzysztof** [comment]
Yeah, something went wrong with commit.
