### ISSUE TITLE
Package ‘bdl’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by lwawrowski** [statisticspoland/R_Package_to_API_BDL#20]
Package was archived on 2020-06-15 and can be no longer installed from CRAN. When we could expect a corrected version?

**Comment by MarcinKosinski** [comment]
@KaniaKrzysztof cc

**Comment by KaniaKrzysztof** [comment]
@lwawrowski We will try to resubmit to CRAN next week

**Comment by KaniaKrzysztof** [comment]
Package is back on CRAN :)
