### ISSUE TITLE
2 author fields in the DESCRIPTION

### ISSUE THREAD

**Issue by MarcinKosinski** [statisticspoland/R_Package_to_API_BDL#3]
If you got this https://github.com/statisticspoland/R_Package_to_API_BDL/blob/master/DESCRIPTION#L6
you can remove this https://github.com/statisticspoland/R_Package_to_API_BDL/blob/master/DESCRIPTION#L22

**Comment by KaniaKrzysztof** [comment]
Fixed in c700442

**Comment by MarcinKosinski** [comment]
@KaniaKrzysztof I think there are still 2 authors fields in the DESCRIPTION
