### ISSUE TITLE
Vignette as an introduction to the package

### ISSUE THREAD

**Issue by MarcinKosinski** [statisticspoland/R_Package_to_API_BDL#9]
For now, I am not quite sure from which function I should start to build the whole workflow for the package. @KaniaKrzysztof can you provide a basic Vignette http://r-pkgs.had.co.nz/vignettes.html explaining the typical workflow, applications and the usage of the package?

**Comment by MarcinKosinski** [comment]
It took me a while to find out something in the `docs/` that is not yet hosted as a website, but for sure is not in the package when it's built locally.

What about developing a vignette in `vignettes` directory and providing the website for the package as a pkgdown website https://pkgdown.r-lib.org/ ?

**Comment by KaniaKrzysztof** [comment]
Fixed in 97781fd9 and f20a2e7b
